//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 09:49:51 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/javaguys/webservices/getUserServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.javaguys.webservices.getuserservices;
